name: billing
description: "A billing application write by flutter."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2025.06.05+1

environment:
  sdk: ^3.8.1
  
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.5
  path: ^1.9.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  fl_chart: ^1.0.0
  http: ^1.4.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  go_router: ^15.1.2
  shared_preferences: ^2.5.3
  grouped_list: ^6.0.0
  csv: ^6.0.0
  file_picker: ^10.1.9
  table_calendar: ^3.2.0
  excel: ^4.0.6
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10
  flutter_animate: ^4.5.2
  fluttertoast: ^8.2.12
  archive: ^3.6.1
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: MiFont
      fonts:
        - asset: assets/fonts/MiSans-Semibold.ttf
          weight: 400
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  